[default]
tmp_dir = "./output"
bin_dir = "./bin"

[[binary]]
repo = "BurntSushi/ripgrep"
asset_download_filename = "ripgrep-{version}-x86_64-unknown-linux-musl.tar.gz"
src = "ripgrep-{version}-x86_64-unknown-linux-musl/rg"
dst = "rg"

[[binary]]
repo = "sharkdp/bat"
asset_download_filename = "bat-v{version}-x86_64-unknown-linux-musl.tar.gz"
src = "bat-v{version}-x86_64-unknown-linux-musl/bat"
dst = "bat"

[[binary]]
repo = "sharkdp/fd"
asset_download_filename = "fd-v{version}-x86_64-unknown-linux-musl.tar.gz"
src = "fd-v{version}-x86_64-unknown-linux-musl/fd"
dst = "fd"

[[binary]]
repo = "neovim/neovim"
asset_download_filename = "nvim.appimage"
src = "nvim.appimage"
dst = "nvim"

[[binary]]
repo = "dbrgn/tealdeer"
asset_download_filename = "tldr-linux-x86_64-musl"
src = "tldr-linux-x86_64-musl"
dst = "tldr"

[[binary]]
repo = "ogham/exa"
asset_download_filename = "exa-linux-x86_64-{version}.zip"
src = "exa-linux-x86_64"
dst = "exa"
