[default]
tmp_dir = "./output"
bin_dir = "./bin"

[[binary]]
owner = "BurntSushi"
repo = "ripgrep"
asset_download_filename = "ripgrep-12.1.1-x86_64-unknown-linux-musl.tar.gz"
src = "ripgrep-12.1.1-x86_64-unknown-linux/musl/rg"
dst = "rg"
